# Generated by Django 4.2.1 on 2023-07-12 01:23

from django.db import migrations, models
import maintenance_management.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesestimate',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='documents', validators=[maintenance_management.accounts.validators.validate_file_size]),
        ),
    ]
