# Generated by Django 4.2.1 on 2023-07-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesestimate',
            name='assignment',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='supervisor.assignment'),
            preserve_default=False,
        ),
    ]
