# Generated by Django 4.2.1 on 2023-07-25 08:01

from django.db import migrations, models
import maintenance_management.contractors.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_expensesestimate_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(validators=[maintenance_management.contractors.validators.meeting_is_in_the_future_validator]),
        ),
    ]
