# Generated by Django 4.2.1 on 2023-07-16 05:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import maintenance_management.accounts.managers
import maintenance_management.accounts.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ForeignKey(help_text='The group this user belongs to. A user will get all permissions granted to their group.', on_delete=django.db.models.deletion.RESTRICT, related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', maintenance_management.accounts.managers.AppUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterInvitation',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('secondary_email', models.EmailField(help_text='You will get a copy of the invitation to be sure sending was properly handled', max_length=254, verbose_name='Your Email:')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='AppUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), maintenance_management.accounts.validators.only_letters_validator, maintenance_management.accounts.validators.first_char_validation])),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), maintenance_management.accounts.validators.only_letters_validator, maintenance_management.accounts.validators.first_char_validation])),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images', validators=[maintenance_management.accounts.validators.validate_file_size])),
                ('expertise', models.CharField(blank=True, choices=[('Networking', 'Networking'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Structural Integrity', 'Structural Integrity'), ('Security Systems', 'Security Systems'), ('Landscaping', 'Landscaping')], default='Not suitable', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.company')),
            ],
        ),
    ]
