# Generated by Django 4.2.1 on 2023-07-06 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicRegisterInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company')),
            ],
        ),
    ]
