# Generated by Django 4.2.1 on 2023-07-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_dynamicregisterinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicregisterinvitation',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
