# Generated by Django 4.2.1 on 2023-07-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuserprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('Networking', 'Networking'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Structural Integrity', 'Structural Integrity'), ('Security Systems', 'Security Systems'), ('Landscaping', 'Landscaping')], default='Not suitable', max_length=20),
        ),
    ]
