# Generated by Django 4.2.1 on 2023-08-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuserprofile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuserprofile',
            old_name='profile_picture',
            new_name='file',
        ),
    ]
