# Generated by Django 4.2.1 on 2023-08-08 04:55

from django.db import migrations, models
import maintenance_management.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuserprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinvitation',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[maintenance_management.accounts.validators.validate_user_is_not_already_registered]),
        ),
    ]
