# Generated by Django 4.2.1 on 2023-07-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaladdressinformation',
            options={'verbose_name_plural': 'Additional address information'},
        ),
    ]
