# Generated by Django 4.2.1 on 2023-07-10 13:19

from django.db import migrations, models
import maintenance_management.estate.validators


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(max_length=50, validators=[maintenance_management.estate.validators.city_name_validation]),
        ),
    ]
