# Generated by Django 4.2.1 on 2023-08-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_alter_additionaladdressinformation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='picture',
            new_name='file',
        ),
    ]
