# Generated by Django 4.2.1 on 2023-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_alter_building_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
