# Generated by Django 4.2.1 on 2023-07-11 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maintenance_management.accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_company_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', validators=[maintenance_management.accounts.validators.validate_file_size])),
                ('report_status', models.CharField(default='Pending', max_length=50)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
