# Generated by Django 4.2.1 on 2023-07-16 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maintenance_management.accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', validators=[maintenance_management.accounts.validators.validate_file_size])),
                ('report_status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Done', 'Done'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('Networking', 'Networking'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Structural Integrity', 'Structural Integrity'), ('Security Systems', 'Security Systems'), ('Landscaping', 'Landscaping'), ('Other', 'Other')], default='Other', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Good'), (4, 'Very good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('service_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.servicereport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
