# Generated by Django 4.2.1 on 2023-08-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicereport',
            old_name='image',
            new_name='file',
        ),
    ]
