# Generated by Django 4.2.1 on 2023-08-02 09:17

from django.db import migrations, models
import maintenance_management.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_image_servicereport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[maintenance_management.accounts.validators.validate_file_size], verbose_name='Image'),
        ),
    ]
