# Generated by Django 4.2.1 on 2023-07-11 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_servicereport_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
