# Generated by Django 4.2.1 on 2023-07-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_servicereport_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='report_type',
            field=models.CharField(choices=[('Networking', 'Networking'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Structural Integrity', 'Structural Integrity'), ('Security Systems', 'Security Systems'), ('Landscaping', 'Landscaping'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='report_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Done', 'Done'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
