# Generated by Django 4.2.1 on 2023-07-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('business_field', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_information', models.TextField(blank=True, max_length=500, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
