# Generated by Django 4.2.1 on 2023-08-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_company_options_company_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_logo',
            new_name='file',
        ),
    ]
