# Generated by Django 4.2.1 on 2023-08-02 09:17

from django.db import migrations, models
import maintenance_management.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_company_logo_company_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[maintenance_management.accounts.validators.validate_file_size], verbose_name='Company Logo'),
        ),
    ]
