# Generated by Django 4.2.1 on 2023-07-11 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_servicereport_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_required', models.BooleanField(blank=True)),
                ('expense_estimate_available', models.BooleanField(blank=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assignment_status', models.CharField(default='Pending', max_length=50)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_information', to=settings.AUTH_USER_MODEL)),
                ('service_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.servicereport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
