# Generated by Django 4.2.1 on 2023-07-14 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0002_alter_expensesestimate_attached_file'),
        ('supervisor', '0002_alter_assignments_assignment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
    ]
