# Generated by Django 4.2.1 on 2023-12-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_alter_assignment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Pending', max_length=8),
        ),
    ]
